(()=>{
const ACCOUNTS=[
{id:'human',name:'Nguyễn Minh An',email:'human@aios.demo',password:'demo',roles:['Giảng viên','Chủ nhiệm đề tài'],defaultRole:'Giảng viên',plane:'human',authority:'Teaching & Research scope'},
{id:'leader',name:'Trần Thu Hà',email:'leader@aios.demo',password:'demo',roles:['Hiệu trưởng'],defaultRole:'Hiệu trưởng',plane:'leadership',authority:'Institutional scope'},
{id:'admin',name:'Lê Quốc Nam',email:'admin@aios.demo',password:'demo',roles:['Platform Admin','Data Steward'],defaultRole:'Platform Admin',plane:'admin',authority:'Platform operations scope'}];
const DOMAINS=[['LIS','Learning','Học tập, chương trình, đánh giá'],['RIS','Research','Nghiên cứu, đề tài, công bố'],['SIS','Student','Người học và hành trình học tập'],['PIS','People','Nhân sự, năng lực, phân công'],['QIS','Quality','Chất lượng, minh chứng, cải tiến'],['OIS','Operations','Vận hành và dịch vụ']];
const ZONES=[['D0','Foundation / Master','Identity, tổ chức, CTĐT, quy định'],['D1','Operational / Living','Work, event, trạng thái vận hành'],['D2','AI Working / Ephemeral','Scratch, extraction, draft — không authoritative'],['D3','Candidate / Proposed','Đề xuất, mapping, draft decision'],['D4','Derived Intelligence','Inference, prediction, recommendation'],['D5','Memory / Evidence / Audit','Decision, outcome, provenance, audit']];
const WORK=[{id:'W-1024',title:'Rà soát đề cương học phần AI',domain:'LIS',status:'Cần xử lý',risk:'action',due:'28/09'},{id:'W-1031',title:'Phê duyệt minh chứng đề tài cấp trường',domain:'RIS',status:'Chờ quyết định',risk:'risk',due:'29/09'},{id:'W-1044',title:'Cập nhật hồ sơ năng lực',domain:'PIS',status:'Đang thực hiện',risk:'',due:'03/10'}];
const I18N={vi:{overview:'Tổng quan',work:'Công việc',catalog:'Catalog',data:'Dữ liệu',workspace:'Không gian',ai:'AI',notifications:'Thông báo',admin:'Quản trị',logout:'Đăng xuất'},en:{overview:'Overview',work:'Work',catalog:'Catalog',data:'Data',workspace:'Workspace',ai:'AI',notifications:'Notifications',admin:'Administration',logout:'Sign out'},zh:{overview:'总览',work:'工作',catalog:'目录',data:'数据',workspace:'工作空间',ai:'AI',notifications:'通知',admin:'管理',logout:'退出'}};
let state={user:null,role:null,view:'overview',locale:localStorage.getItem('aios.locale')||'vi',records:JSON.parse(localStorage.getItem('aios.records')||'[]'),messages:[]};
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function save(){localStorage.setItem('aios.records',JSON.stringify(state.records));localStorage.setItem('aios.locale',state.locale)}
function login(){document.body.innerHTML=`<div class="login"><div class="login-card"><div class="login-brand"><h1>AIOS</h1><h3>AI Operating System</h3><p>Một Experience Shell thống nhất cho Human, Leadership và Administration. Workspace thay đổi theo Identity, Role, Context và Authority.</p><p class="small" style="color:#d8efea">Prototype dùng dữ liệu synthetic. Không nhập dữ liệu nhạy cảm thật.</p></div><div class="login-form"><h2>Đăng nhập AIOS</h2><div class="field"><label>Email</label><input id="email" value="human@aios.demo"></div><div class="field"><label>Mật khẩu</label><input id="password" type="password" value="demo"></div><button class="btn" id="loginBtn">Đăng nhập</button><div id="loginError" class="small" style="color:var(--danger);margin-top:8px"></div><div class="demo-accounts"><b>Tài khoản thử nghiệm</b>${ACCOUNTS.map(a=>`<div class="demo" data-email="${a.email}"><b>${a.name}</b><div class="small">${a.email} · ${a.defaultRole}</div></div>`).join('')}</div></div></div></div>`;document.querySelectorAll('.demo').forEach(x=>x.onclick=()=>{$('#email').value=x.dataset.email;$('#password').value='demo'});$('#loginBtn').onclick=()=>{let u=ACCOUNTS.find(a=>a.email===$('#email').value.trim()&&a.password===$('#password').value);if(!u){$('#loginError').textContent='Sai tài khoản hoặc mật khẩu demo.';return}state.user=u;state.role=u.defaultRole;state.view='overview';render()}}
function t(k){return I18N[state.locale]?.[k]||k}
function nav(){let base=['overview','work','catalog','data','workspace','ai','notifications'];if(state.user.plane==='admin')base.push('admin');return base}
function shell(content){return `<header class="topbar"><div class="brand">AIOS</div><nav class="nav">${nav().map(k=>`<button data-view="${k}" class="${state.view===k?'active':''}">${t(k)}</button>`).join('')}</nav><div class="top-actions"><select id="locale"><option value="vi">VI</option><option value="en">EN</option><option value="zh">中文</option></select><div class="avatar">${esc(state.user.name.split(' ').slice(-1)[0][0])}</div><button class="btn secondary" id="logout">${t('logout')}</button></div></header><div class="contextbar"><span>Identity: <strong>${esc(state.user.name)}</strong></span><span>Role: <select id="role">${state.user.roles.map(r=>`<option ${r===state.role?'selected':''}>${esc(r)}</option>`).join('')}</select></span><span>Context: <strong>${state.user.plane}</strong></span><span>Authority: <strong>${esc(state.user.authority)}</strong></span></div><main class="shell">${content}</main><div id="drawerHost"></div>`}
function hero(title,desc,tag='AIOS LIVE PROTOTYPE'){return `<div class="hero"><div><span class="badge">${tag}</span><h1>${title}</h1><p>${desc}</p></div></div>`}
function metrics(items){return `<div class="metrics">${items.map(x=>`<div class="card metric"><div class="k">${x[0]}</div><div class="v">${x[1]}</div><div class="small">${x[2]||''}</div></div>`).join('')}</div>`}
function workList(){return `<div class="list">${WORK.map(w=>`<div class="item"><div><h3>${w.title}</h3><p>${w.id} · ${w.domain} · Hạn ${w.due}</p></div><span class="status ${w.risk}">${w.status}</span></div>`).join('')}</div>`}
function overview(){if(state.user.plane==='leadership')return hero('Executive Command Center','Outcome, bottleneck, decision và risk trong institutional scope')+metrics([['Outcome','84%','mục tiêu đang đúng hướng'],['Bottleneck','3','cần điều phối'],['Decision','5','đang chờ quyết định'],['Risk','2','mức cao']])+`<div class="grid2"><section class="card"><div class="section-title"><h2>Điểm nghẽn & quyết định</h2></div>${workList()}</section><section class="card ai-panel"><div class="section-title"><h2>Executive AI</h2></div><div class="notice">AI tổng hợp: 2 rủi ro cần xem trong 7 ngày; 1 dependency ảnh hưởng RIS và QIS.</div><div class="toolbar" style="margin-top:8px"><button class="btn ghost" data-aiq="Việc gì cần tôi quyết định?">Việc cần quyết định?</button><button class="btn ghost" data-aiq="Rủi ro nào đang tăng?">Rủi ro tăng?</button></div></section></div>`;
if(state.user.plane==='admin')return hero('Administration Workspace','Vận hành AIOS theo Human + AI; technical administration không phải institutional authority')+metrics([['Core','Healthy','services nominal'],['Domains','6','registry active'],['Agents','4','scoped agents'],['Changes','1','awaiting review']])+`<div class="admin-grid">${['System Overview','Domain Registry','Capability Registry','Data & Semantic','Agent Registry','Model Registry','Security & Privacy','Change Management'].map(x=>`<div class="card admin-tile"><b>${x}</b><p class="small">Mở workspace quản trị và AI copilot theo authority.</p></div>`).join('')}</div>`;
return hero(`Xin chào, ${esc(state.user.name)}`,'Workspace cá nhân được compose theo role, context, authority và work hiện tại')+metrics([['Cần xử lý','3','ưu tiên hôm nay'],['Đang làm','7','work đang mở'],['Chờ quyết định','2','cần Human action'],['Rủi ro','1','cần chú ý']])+`<div class="grid2"><section class="card"><div class="section-title"><h2>Công việc của tôi</h2><button class="btn ghost" data-view="work">Xem tất cả</button></div>${workList()}</section><section class="card ai-panel"><div class="section-title"><h2>AI Assistant</h2></div><div class="notice">AI có context: ${esc(state.role)} · ${esc(state.user.authority)}. Recommendation không phải Decision.</div><div class="toolbar" style="margin-top:8px"><button class="btn ghost" data-aiq="Tóm tắt việc cần làm hôm nay">Tóm tắt hôm nay</button><button class="btn ghost" data-aiq="Phân tích công việc có rủi ro">Phân tích rủi ro</button></div></section></div>`}
function work(){return hero('Work','Work là đơn vị vận hành, liên kết decision, evidence và outcome')+`<section class="card"><div class="section-title"><h2>Work queue</h2><button class="btn" id="newWork">+ Tạo work</button></div>${workList()}</section>`}
function catalog(){return hero('Domain Catalog','Domain là cấu hình trên AIOS Core; capability tái sử dụng xuyên Domain')+`<div class="catalog">${DOMAINS.map(d=>`<div class="tile" data-domain="${d[0]}"><div class="code">${d[0]}</div><div class="name">${d[1]}</div><div class="desc">${d[2]}</div></div>`).join('')}</div>`}
function data(){return hero('Living Data & Memory Fabric','One semantic reality · many physical stores · one governed data fabric')+`<div class="data-zones">${ZONES.map(z=>`<div class="card zone"><strong>${z[0]} · ${z[1]}</strong><div class="small">${z[2]}</div></div>`).join('')}</div><section class="card" style="margin-top:10px"><div class="section-title"><h2>Dữ liệu thử nghiệm</h2><button class="btn" id="addRecord">+ Nhập dữ liệu</button></div>${state.records.length?`<table class="table"><thead><tr><th>Loại</th><th>Nội dung</th><th>Zone</th><th>Validation</th></tr></thead><tbody>${state.records.map(r=>`<tr><td>${esc(r.type)}</td><td>${esc(r.value)}</td><td>${esc(r.zone)}</td><td>${esc(r.validation)}</td></tr>`).join('')}</tbody></table>`:'<div class="empty">Chưa có record thử nghiệm. Dữ liệu được lưu cục bộ trong trình duyệt.</div>'}</section>`}
function workspace(){return hero('Dynamic Workspace','ONE HUMAN · ONE IDENTITY · MANY ROLE ASSIGNMENTS · ONE CURRENT CONTEXT')+`<div class="grid3"><div class="card"><b>Identity</b><p>${esc(state.user.name)}</p><div class="small">${esc(state.user.email)}</div></div><div class="card"><b>Active Role</b><p>${esc(state.role)}</p><div class="small">Role switch không cộng dồn authority.</div></div><div class="card"><b>Authority Context</b><p>${esc(state.user.authority)}</p><div class="small">Consequential actions phải kiểm tra authority.</div></div></div>`}
function ai(){return hero('AI Workspace','Contextual AI; analysis và recommendation không tự trở thành institutional decision')+`<div class="grid2"><section class="card ai-panel"><div class="section-title"><h2>Ask AI</h2><span class="badge">Provider Adapter</span></div><div id="chat" class="ai-chat">${state.messages.length?state.messages.map(m=>`<div class="msg ${m.who}">${esc(m.text)}</div>`).join(''):'<div class="msg ai">Tôi đang hoạt động ở chế độ prototype. Có thể phân tích context và dữ liệu synthetic; provider AI thật cần endpoint/token phía server để không lộ khóa bí mật.</div>'}</div><div class="composer"><input id="aiInput" placeholder="Hỏi AI về công việc, dữ liệu, rủi ro..."><button class="btn" id="sendAI">Gửi</button></div></section><section class="card"><h2 style="font-size:14px">AI Authority Boundary</h2><div class="notice">AI được phân tích, tóm tắt, đề xuất và chuẩn bị artifact.</div><div class="notice danger-note" style="margin-top:7px">AI không tự phê duyệt quyết định có hậu quả thể chế.</div><p class="small">Context: ${esc(state.role)} · ${esc(state.user.authority)}</p></section></div>`}
function notifications(){return hero('Thông báo','Action required, decision required, risk và system notices')+`<section class="card"><div class="list"><div class="item"><div><h3>2 quyết định đang chờ</h3><p>RIS · authority scope phù hợp</p></div><span class="status action">Action</span></div><div class="item"><div><h3>1 work có nguy cơ quá hạn</h3><p>LIS · deadline 28/09</p></div><span class="status risk">Risk</span></div></div></section>`}
function admin(){return hero('AIOS Administration','Human + AI platform operations')+`<div class="admin-grid">${['System Overview','Domain Registry','Capability Registry','Data & Semantic Governance','Agent Registry','Model Registry','Policy Runtime','Integration Registry','Workspace Configuration','Security & Privacy','Change Management','Incident Management'].map(x=>`<div class="card admin-tile"><b>${x}</b><p class="small">Registry-driven · auditable · scoped authority</p></div>`).join('')}</div>`}
function render(){if(!state.user){login();return}let views={overview,work,catalog,data,workspace,ai,notifications,admin};document.body.innerHTML=shell((views[state.view]||overview)());$('#locale').value=state.locale;$('#locale').onchange=e=>{state.locale=e.target.value;save();render()};$('#role').onchange=e=>{state.role=e.target.value;render()};$('#logout').onclick=()=>{state.user=null;render()};document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{state.view=b.dataset.view;render()});document.querySelectorAll('[data-aiq]').forEach(b=>b.onclick=()=>{state.view='ai';state.messages.push({who:'user',text:b.dataset.aiq});state.messages.push({who:'ai',text:prototypeAI(b.dataset.aiq)});render()});if($('#sendAI'))$('#sendAI').onclick=sendAI;if($('#aiInput'))$('#aiInput').onkeydown=e=>{if(e.key==='Enter')sendAI()};if($('#addRecord'))$('#addRecord').onclick=openRecord;if($('#newWork'))$('#newWork').onclick=()=>drawer('Tạo Work','Prototype đã có Work contract surface; ghi dữ liệu thật sẽ được nối backend ở bản runtime.');document.querySelectorAll('[data-domain]').forEach(x=>x.onclick=()=>drawer(`${x.dataset.domain} Domain`,DOMAINS.find(d=>d[0]===x.dataset.domain)?.[2]+' · Domain được sinh từ registry, không phải app silo.'))}
function prototypeAI(q){let l=q.toLowerCase();if(l.includes('rủi ro'))return 'Phân tích prototype: W-1031 cần quyết định và có dependency với evidence; W-1024 gần deadline. Đây là recommendation, chưa phải decision.';if(l.includes('hôm nay'))return 'Ưu tiên: (1) rà soát W-1024, (2) chuẩn bị evidence cho W-1031, (3) cập nhật W-1044. Tôi có thể mở từng work để phân tích tiếp.';return `Tôi đã nhận yêu cầu trong context ${state.role}. Bản prototype đang dùng AI adapter cục bộ; khi nối backend provider, cùng giao diện này sẽ gọi model thật mà không lộ API key.`}
async function sendAI(){let i=$('#aiInput');if(!i||!i.value.trim())return;let q=i.value.trim();state.messages.push({who:'user',text:q});render();try{let r=await fetch('/api/ai',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({prompt:q,context:{identity:state.user.name,role:state.role,plane:state.user.plane,authority:state.user.authority}})});if(!r.ok)throw new Error('provider unavailable');let d=await r.json();state.messages.push({who:'ai',text:d.text})}catch(e){state.messages.push({who:'ai',text:prototypeAI(q)})}render()}
function drawer(title,body){$('#drawerHost').innerHTML=`<aside class="drawer"><div class="drawer-head"><h2>${esc(title)}</h2><button class="close">Đóng</button></div><p>${esc(body)}</p></aside>`;$('.close').onclick=()=>$('#drawerHost').innerHTML=''}
function openRecord(){let html=`<aside class="drawer"><div class="drawer-head"><h2>Nhập dữ liệu thử nghiệm</h2><button class="close">Đóng</button></div><div class="notice">Không nhập dữ liệu cá nhân/nhạy cảm thật vào prototype.</div><div class="field"><label>Loại</label><select id="rtype"><option>Document</option><option>Assertion</option><option>Evidence</option><option>Work data</option></select></div><div class="field"><label>Nội dung</label><textarea id="rvalue" rows="5"></textarea></div><div class="field"><label>Data zone</label><select id="rzone">${ZONES.map(z=>`<option>${z[0]}</option>`).join('')}</select></div><button class="btn" id="saveRecord">Lưu record</button></aside>`;$('#drawerHost').innerHTML=html;$('.close').onclick=()=>$('#drawerHost').innerHTML='';$('#saveRecord').onclick=()=>{state.records.push({type:$('#rtype').value,value:$('#rvalue').value,zone:$('#rzone').value,validation:'candidate'});save();render()}}
render();
})();
